## Roster

In [4]:
#import import_ipynb
#import os
import pandas as pd
import numpy as np
from scipy import stats
import igraph as ig
import matplotlib.pyplot as plt
import seaborn as sns 
import plotly.express as px
import random
from numpy import random as nprando
from datetime import datetime, date, time, timedelta
import pyreadstat

######################################################################################### 

##SETUP##
sns.set()
nprando.seed(111)
plt.rcParams.update(plt.rcParamsDefault)
plt.rcParams.update({'figure.figsize': (12, 8)})
pd.set_option("display.max_columns",None)

##VARIABLES##
rs = "./Data/Roster_LRES_Baseline_Anon_V1.0.0.dta"
clm = "./Data/ClaimFamilyData_LRES_SurveyData_Merge_V1.0.0.dta"

##IMPORT##
df_rs , meta = pyreadstat.read_dta(rs)
df_clm , meta = pyreadstat.read_dta(clm)

In [3]:
df_rs.describe(include="all")

,claim_id,bl_hhid,pid,bl_r_outcome,bl_r_treatment,bl_r_claim_type,bl_r_hhmemid,bl_r_intrv_team,bl_r_intrv_code,bl_r_intrv_date,bl_r_csm,bl_r_chosen,bl_r_duration,bl_r_cons,bl_r_odi,bl_r_gen,bl_r_dob_m,bl_r_dob_y,bl_r_age,bl_r_adult,bl_r_mem,bl_r_pres,bl_r_relben,bl_r_relodi,bl_r_relodi_o,bl_r_claim,bl_r_popgrp,bl_r_popgrp_o,bl_r_absm,bl_r_eatd,bl_r_lng,bl_r_edschgrd,bl_r_edschgrd_o,bl_r_edter,bl_r_edterlev,bl_r_parhpid,bl_r_mar,bl_r_noparh
count,2683.000000,2.683000e+03,2.683000e+03,2683.0,2683.000000,2683.000000,2681.0,2683.000000,2670.0,2683,2683.000000,2683.000000,2683.000000,2681.0,2676.0,2678.0,2678.0,2678.0,2678.0,78.0,2678.0,2678.0,2042.0,2678.0,2683,2548.0,2678.0,2683,2678.0,2678.0,2678.0,2678.0,2683,2006.0,488.0,2008.0,528.0,1074.0
unique,NaN,NaN,NaN,NaN,NaN,NaN,152.0,NaN,73.0,654,NaN,NaN,NaN,1.0,2.0,4.0,14.0,94.0,97.0,3.0,2.0,2.0,13.0,10.0,42,3.0,8.0,5,15.0,11.0,12.0,23.0,8,5.0,20.0,713.0,5.0,6.0
top,NaN,NaN,NaN,NaN,NaN,NaN,301.0,NaN,54.0,"Oct 30, 2019 9:05:50 Am",NaN,NaN,NaN,1.0,2.0,2.0,3.0,9999.0,2.0,1.0,1.0,1.0,3.0,4.0,,-3.0,1.0,,0.0,7.0,2.0,12.0,,2.0,19.0,0.0,1.0,5.0
freq,NaN,NaN,NaN,NaN,NaN,NaN,414.0,NaN,231.0,18,NaN,NaN,NaN,2681.0,2658.0,1409.0,259.0,57.0,62.0,45.0,2657.0,2604.0,793.0,669.0,2208,1828.0,1809.0,2666,2437.0,2534.0,907.0,760.0,2676,1466.0,110.0,1055.0,417.0,948.0
mean,485.835632,4.858359e+07,4.861156e+07,1.0,0.544540,1.406262,NaN,234.989564,NaN,NaN,1.723071,1.377190,3106.788669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,206.344441,2.063445e+07,2.064523e+07,0.0,0.498105,0.491226,NaN,416.394898,NaN,NaN,0.447564,0.484773,1924.114555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,8.000000,8.000010e+05,8.000040e+05,1.0,0.000000,1.000000,NaN,1.000000,NaN,NaN,1.000000,1.000000,167.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,364.000000,3.640000e+07,3.640430e+07,1.0,0.000000,1.000000,NaN,7.000000,NaN,NaN,1.000000,1.000000,1915.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,561.000000,5.610001e+07,5.610002e+07,1.0,1.000000,1.000000,NaN,10.000000,NaN,NaN,2.000000,1.000000,2774.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,657.000000,6.570005e+07,6.574818e+07,1.0,1.000000,2.000000,NaN,14.000000,NaN,NaN,2.000000,2.000000,3921.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,757.000000,7.570005e+07,7.575330e+07,1.0,1.000000,2.000000,NaN,1000.000000,NaN,NaN,2.000000,2.000000,19972.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_clm.describe(include="all")

,claim_id,bl_c_status,bl_c_province,bl_c_district,bl_c_estimatedbudget,bl_c_estimatedoptions,bl_c_landtype,bl_c_lodgementtype,bl_c_no_clmnt,bl_c_no_odi,bl_c_no_fam,bl_c_no_famben,bl_c_no_famben_fem,bl_c_avg_age,bl_c_no_odiben,bl_c_no_spouseben,bl_c_no_firstben,bl_c_no_secondben,bl_c_no_thirdben,bl_c_no_fourthben,bl_c_no_famtraced,bl_c_no_famphase,bl_c_no_famgroup,bl_c_no_prop,bl_c_tot_propextent_ha,bl_c_no_land,bl_c_tot_landextent_ha,bl_c_no_landtraced,bl_c_no_landphase,bl_c_no_hhid,bl_c_no_pid,relationship_id,relationshipodi,ben_id,ben_parent_id,phase_id,group_id,createddate,modifieddate,createdby,modifiedby,claimant,lastname,firstname,gender,idno,dob,deceased,disabled,married,eligible,poa,homenumber,cellnumber,physicaladdress,city,zipcode,province_id,country,dispossession,noinhouse,tracestatus,provinceben,benname,addressdetails,age
count,3123.000000,3123,3123,3123,8.460000e+02,3123,3123,3123,3123.000000,3123.000000,3123.000000,3123.000000,3014.000000,2722.000000,1583.000000,838.000000,2498.000000,2509.000000,1439.000000,584.000000,3105.000000,3123.0,3123.0,3115.000000,3115.000000,2484.000000,2484.000000,2484.000000,2484.000000,3123.000000,3123.000000,3123.000000,3123,3123.000000,3123,3123,3123,2.800000e+01,1.700000e+01,3123,3123,3123.000000,3123,3123,3123,3123,1.487000e+03,3123.000000,3123.000000,3123.000000,3123.000000,3123.000000,3123,3123,3123,3123,3123,2667.0,3123,3123.000000,139.0,3123,3123,3123,3123,1487.000000
unique,NaN,9,6,17,NaN,2,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,858,1,1,NaN,NaN,2,2,NaN,694,2452,3,1779,NaN,NaN,NaN,NaN,NaN,NaN,227,864,941,247,204,9.0,6,NaN,10.0,9,10,2932,1013,NaN
top,NaN,Settlement,Mpumalanga,Nkangala,NaN,Land Restoration,Rural,Family,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Grandchild,NaN,,11,11,NaN,NaN,,,NaN,Not Identified,,Female,,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,6.0,South Africa,NaN,2.0,,Mpumalanga,Not Identified (D),", , Mpumalanga, South Africa,",NaN
freq,NaN,1764,1197,622,NaN,1710,2398,3123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1098,NaN,218,3123,3123,NaN,NaN,3121,3121,NaN,115,129,1265,1324,NaN,NaN,NaN,NaN,NaN,NaN,2863,2075,1894,1542,2552,913.0,3072,NaN,38.0,1535,913,115,547,NaN
mean,521.298111,NaN,NaN,NaN,6.315011e+05,NaN,NaN,NaN,2.622158,6.177073,109.106308,66.030740,32.935302,57.828803,5.095389,3.496420,26.616894,29.983260,25.047950,29.892123,31.325604,1.0,1.0,1.038844,4037.891890,1.932367,680.080875,1.297907,0.141707,20.851425,50.677874,3.534422,NaN,5950.967339,NaN,NaN,NaN,1.893556e+12,1.896873e+12,NaN,NaN,0.023055,NaN,NaN,NaN,NaN,2.625782e+11,0.261287,0.000320,0.010247,0.825168,0.022414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003842,NaN,NaN,NaN,NaN,NaN,53.180901
std,202.657456,NaN,NaN,NaN,8.942719e+05,NaN,NaN,NaN,4.392795,6.737056,80.183124,53.136556,27.365726,10.132293,4.604497,1.741849,32.178967,33.550703,15.455749,36.227796,27.626337,0.0,0.0,0.232478,40759.119981,1.567727,938.499416,1.700673,0.348820,26.048857,58.457253,1.139677,NaN,2865.434899,NaN,NaN,NaN,4.244715e+09,7.438849e+08,NaN,NaN,0.150101,NaN,NaN,NaN,NaN,6.937868e+11,0.439406,0.017894,0.100721,0.379884,0.148051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.061878,NaN,NaN,NaN,NaN,NaN,21.978613
min,8.000000,NaN,NaN,NaN,4.437880e+04,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,39.555557,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,NaN,7.000000,NaN,NaN,NaN,1.888109e+12,1.896608e+12,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,-1.863994e+12,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,5.000000
25%,446.000000,NaN,NaN,NaN,1.109470e+05,NaN,NaN,NaN,1.000000,1.000000,29.000000,19.000000,7.000000,51.470589,1.000000,1.000000,4.000000,7.000000,15.000000,1.000000,6.000000,1.0,1.0,1.000000,3.134900,1.000000,9.222200,0.000000,0.000000,3.000000,9.000000,3.000000,NaN,3882.000000,NaN,NaN,NaN,1.888732e+12,1.896609e+12,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,-1.996272e+11,0.000000,0.000000,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,38.000000
50%,624.000000,NaN,NaN,NaN,2.000000e+05,NaN,NaN,NaN,1.000000,2.000000,102.000000,53.000000,17.000000,52.634148,2.000000,4.000000,11.500000,14.000000,27.000000,2.000000,24.000000,1.0,1.0,1.000000,319.094299,1.000000,295.321503,1.000000,0.000000,8.000000,21.000000,4.000000,NaN,6186.000000,NaN,NaN,NaN,1.896609e+12,1.896609e+12,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,2.782080e+11,0.000000,0.000000,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,53.000000
75%,657.000000,NaN,NaN,NaN,1.000000e+06,NaN,NaN,NaN,1.000000,10.000000,170.000000,105.000000,60.000000,65.400002,10.000000,5.000000,43.000000,46.000000,39.000000,78.000000,55.000000,1.0,1.0,1.000000,771.632507,2.000000,877.832397,2.000000,0.000000,27.000000,72.000000,4.000000,NaN,7792.500000,NaN,NaN,NaN,1.896609e+12,1.896609e+12,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,7.529760e+11,1.000000,0.000000,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,68.000000
max,757.000000,NaN,NaN,NaN,3.000000e+06,NaN,NaN,NaN,18.000000,19.000000,251.000000,188.000000,86.000000,96.000000,13.000000,5.000000,110.000000,117.000000,46.000000,78.000000,99.000000,1.0,1.0,3.000000,498580.000000,6.000000,3070.510254,6.000000,1.000000,93.000000,218.000000,6.000000,NaN,14298.000000,NaN,NaN,NaN,1.898849e+12,1.898849e+12,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,1.781309e+12,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,121.000000

In [ ]:
df_hhid=df_clm[["bl_c_no_hhid",'bl_c_province']]
df_toi_ct = pd.crosstab(index=df_toi['bl_h_toi'], columns=df_toi['bl_c_province'], rownames=[""], colnames=[""], margins=True, margins_name="Total", normalize=True)
print("--------" + "\n" + '\033[1m' + 'Question: ' + '\033[0m' + meta.column_labels[(meta.column_names).index('bl_h_toi')]  + "\n")
df_toi_ct.astype(float).applymap(lambda x: str(format(x*100,'.2f'))+'%')